name: methflow-0.0.0
channels:
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - conda-forge::ncurses=6.1
  - anaconda::click=7.0
  - anaconda::pyyaml=3.13
  - anaconda::openjdk=8.0.152
  - bioconda::parallel-fastq-dump=0.6.3
  - bioconda::fastqc=0.11.8
  - bioconda::cutadapt=1.18
  - bioconda::trim-galore=0.5.0
  - bioconda::samtools=1.9
  - bioconda::pysam=0.15.1
  - bioconda::bowtie2=2.3.4.3
  - bioconda::bismark=0.20.0
  - bioconda::picard=2.18.21
  - bioconda::gatk=3.8
  - bioconda::qualimap=2.2.2b
  - bioconda::methylextract=1.9.1
  - bioconda::multiqc=1.7
