name: methflow-requirements-0.0.0
channels:
  - conda-forge
  - anaconda
  - r
  - defaults
dependencies:
  - conda-forge::python=3.7.1
  - anaconda::click=7.0
  - anaconda::pyyaml=3.13
  - conda-forge::requests=2.21.0
  - conda-forge::perl=5.26.2
  - anaconda::openjdk=8.0.152
  - r::r-base=3.5.1
  - conda-forge::ncurses=6.1
