name: methflow-requirements-0.0.0
channels:
  - conda-forge
  - anaconda
  - r
  - bioconda
dependencies:
  - anaconda::gcc_linux-64=7.3.0
  - anaconda::gxx_linux-64=7.3.0
  - anaconda::gfortran_linux-64=7.3.
  - conda-forge::curl=7.63.0
  - conda-forge::libcurl=7.63.0
  - r::r-curl=3.2
  - conda-forge::python=3.7.1
  - anaconda::click=7.0
  - anaconda::pyyaml=3.13
  - conda-forge::requests=2.21.0
  - conda-forge::perl=5.26.2
  - anaconda::openjdk=8.0.152
  - r::r-base=3.5.1
  - r::r-rjson=0.2.20
  - conda-forge::ncurses=6.1
  - bioconda::perl-app-cpanminus=1.7044
  - anaconda::libgd=2.2.5
  - bioconda::perl-extutils-pkgconfig=1.16
  - conda-forge::libjpeg-turbo=2.0.1
  - bioconda::perl-getopt-long=2.50
  - bioconda::perl-pod-usage=1.69
